name: smscontroller
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  simple_splashscreen: ^0.1.3
  sqflite: ^1.3.1
  animated_dialog: ^1.0.5
  flutter_phone_direct_caller: ^1.0.1
  sendsms: ^1.0.3
  sms: ^0.2.0
  audioplayers: ^0.16.1
  lite_rolling_switch: ^0.1.1
  webview_flutter: ^0.3.20+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/
    - assets/index.html
    - assets/tik.mp3
  fonts:
    - family: iranSans
      fonts:
        - asset: assets/fonts/iransans.ttf